In [37]:
# Import dependancies
import numpy as np
import statistics


from sklearn import metrics
from sklearn.datasets import load_digits
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans

In [38]:
#import datasets
digits = load_digits()

In [39]:
# flatten the images
n_samples = len(digits.images)

data = digits.images.reshape((n_samples, -1))

In [40]:
#x is feature vector and y is true labels
x = data
y = digits.target

In [41]:
# 10 number of clusters are given as input to k means clustering

kmeans = KMeans(n_clusters = 10, random_state=0)

In [42]:
#Fitting and predicting the clusters
kmeans.fit_predict(x)

array([5, 7, 7, ..., 7, 3, 3])

In [43]:
#Check the cluster and see which true label value frequency is highest inside cluster
assigned_label = kmeans.labels_
true_label = digits.target

temp = []
mat = []
corrected_label = []
for i in range(10):
    for j in range(n_samples):
        if assigned_label[j] == i:
            temp.append(true_label[j])
            mode = statistics.mode(temp)
    corrected_label.append(mode)
    mat = temp
    temp.clear()

print("Most frequent labels of 10 clusters:",corrected_label)

Most frequent labels of 10 clusters: [4, 3, 5, 9, 7, 0, 1, 8, 2, 6]


In [44]:
# Assign most frequent true label value of cluster to all points in the cluster for all clusters

new_label = np.zeros(1797)
for i in range(10):
    for j in range(n_samples):
        if assigned_label[j] == i:
            new_label[j] = corrected_label[i]


In [45]:
#print("Final cluster labels:", new_label)
print("Accuracy:",metrics.fowlkes_mallows_score(true_label, new_label))

Accuracy: 0.702734687012768


In [46]:
confusion = confusion_matrix(true_label, new_label)

print("Confusion_matrix:\n",confusion)

Confusion_matrix:
 [[177   0   0   0   1   0   0   0   0   0]
 [  0  55  24   1   0   1   2   0  99   0]
 [  1   2 148  13   0   0   0   3   8   2]
 [  0   0   0 154   0   2   0   7   7  13]
 [  0   7   0   0 163   0   0   7   4   0]
 [  0   0   0   0   2 136   1   0   0  43]
 [  1   1   0   0   0   0 177   0   2   0]
 [  0   0   0   0   0   0   0 177   2   0]
 [  0   5   3   2   0   4   2   5 100  53]
 [  0  20   0   6   0   6   0   7   2 139]]
